### ISSUE TITLE
jsdom Error on Fresh Install

### ISSUE THREAD

**Issue by dariusk** [FeelTrainCoop/shortcut#120]
Reported by Twitter user `lp_notes`:

I followed the "getting started" guide at https://github.com/FeelTrainCoop/shortcut/wiki/Getting-started-%28for-developers%29, but ran into this error at the "npm start" step:
```bash
 npm start

> shortcut-server@1.1.0 start /Users/linda/Desktop/projects/shortcut/server
> node server.js

No SSL key and/or cert found, not enabling https server
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'paper-jsdom-canvas'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/lindapeng/Desktop/lindaprojects/shortcut/server/routes/anim/animcontrol.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

**Comment by dariusk** [comment]
Fixed in [b05e6da](https://github.com/FeelTrainCoop/shortcut/commit/b05e6da0675dccd97fc34b5b415bf98b159ff865), after spending a few days reproducing discovered there was a `canvas` package compatibility issue.
