### ISSUE TITLE
Cannot build on MacOS using node v12

### ISSUE THREAD

**Issue by jfix** [FeelTrainCoop/shortcut#136]
What are the steps to reproduce this issue?
-------------------------------------------
1. Have a recent MacOS (I encountered the issue on Catalina)
2. Latest `npm`, `node`, Xcode and CLI installed and working
3. Try doing an `npm build` in either `server/` or `client/`
 
What happens?
-------------
`npm build` does not succeed but has errors during the `node-gyp` phase. It seems like it is trying to build a library (Canvas?) but fails. 

👉 **Could it be that the code is intended for node 6 or 8 but I'm using 12?**

```
✘-1 ~/Projects/shortcut/server [master|✔] 
18:45 $ npm install

> canvas@1.6.12 install /Users/jakob/Projects/shortcut/server/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
In file included from ../../nan/nan.h:221:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: warning: 'ToBoolean' is deprecated: ToBoolean can never throw. Use Local version.
      [-Wdeprecated-declarations]
X(Boolean)
^
../../nan/nan_converters_43_inl.h:18:12: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
           ^
<scratch space>:214:1: note: expanded from here
ToBoolean
^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:2567:3: note: 'ToBoolean' has been explicitly marked deprecated here
  V8_DEPRECATED("ToBoolean can never throw. Use Local version.",
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
In file included from ../../nan/nan.h:221:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:40:1: warning: 'BooleanValue' is deprecated: BooleanValue can never throw. Use Isolate version.
      [-Wdeprecated-declarations]
X(bool, Boolean)
^
../../nan/nan_converters_43_inl.h:37:15: note: expanded from macro 'X'
  return val->NAME ## Value(isolate->GetCurrentContext());                     \
              ^
<scratch space>:221:1: note: expanded from here
BooleanValue
^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:2605:3: note: 'BooleanValue' has been explicitly marked deprecated here
  V8_DEPRECATED("BooleanValue can never throw. Use Isolate version.",
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:103:42: error: no viable conversion from 'v8::Isolate *' to 'Local<v8::Context>'
  return scope.Escape(v8::Function::New( isolate
                                         ^~~~~~~
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:183:7: note: candidate constructor (the implicit copy constructor) not viable:
      no known conversion from 'v8::Isolate *' to 'const v8::Local<v8::Context> &' for 1st argument
class Local {
      ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:183:7: note: candidate constructor (the implicit move constructor) not viable:
      no known conversion from 'v8::Isolate *' to 'v8::Local<v8::Context> &&' for 1st argument
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:187:13: note: candidate template ignored: could not match
      'Local<type-parameter-0-0>' against 'v8::Isolate *'
  V8_INLINE Local(Local<S> that)
            ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:4171:22: note: passing argument to parameter 'context' here
      Local<Context> context, FunctionCallback callback,
                     ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:37: error: too few arguments to function call, expected 2, have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:5426:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, Local<String> value);
  ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:58: error: expected '(' for function-style cast or type construction
  return v8::StringObject::New(value).As<v8::StringObject>();
                                         ~~~~~~~~~~~~~~~~^
../../nan/nan_implementation_12_inl.h:337:60: error: expected expression
  return v8::StringObject::New(value).As<v8::StringObject>();
                                                           ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:1063:44: error: no matching member function for call to 'ToString'
      v8::Local<v8::String> string = from->ToString();
                                     ~~~~~~^~~~~~~~
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:2572:44: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:2588:31: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
                Local<String> ToString(Isolate* isolate) const);
                              ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:1073:37: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'char *'
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                    ^~~~
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:2782:26: note: passing argument to parameter 'isolate' here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
                         ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:1847:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
                           ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:1853:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(key, value);
                           ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:1859:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(index, value);
                           ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:1865:32: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
        New(persistentHandle)->Get(New(key).ToLocalChecked()));
                               ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:3457:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:1871:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return scope.Escape(New(persistentHandle)->Get(key));
                                               ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:3457:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:1876:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return scope.Escape(New(persistentHandle)->Get(index));
                                               ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:3461:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
In file included from ../../nan/nan.h:2690:
../../nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(persistent().IsNearDeath());
           ~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: expanded from
      macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
In file included from ../../nan/nan.h:2690:
../../nan/nan_object_wrap.h:67:18: warning: 'MarkIndependent' is deprecated: Weak objects are always considered independent. Use TracedGlobal
      when trying to use EmbedderHeapTracer. Use a strong handle when trying to keep an object alive. [-Wdeprecated-declarations]
    persistent().MarkIndependent();
                 ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:563:3: note: 'MarkIndependent' has been explicitly marked deprecated here
  V8_DEPRECATED(
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
In file included from ../../nan/nan.h:2690:
../../nan/nan_object_wrap.h:124:26: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(wrap->handle_.IsNearDeath());
           ~~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: expanded from
      macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:42:8: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
  Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, argv);
       ^
../../nan/nan.h:958:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:63:8: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
  Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, data_argv);
       ^
../../nan/nan.h:958:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:71:8: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
  Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, end_argv);
       ^
../../nan/nan.h:958:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/Canvas.cc:60:75: error: too few arguments to function call, single argument 'context' was not specified
  Nan::Set(target, Nan::New("Canvas").ToLocalChecked(), ctor->GetFunction());
                                                        ~~~~~~~~~~~~~~~~~ ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:5995:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/Canvas.cc:74:57: error: too few arguments to function call, single argument 'context' was not specified
  if (info[0]->IsNumber()) width = info[0]->Uint32Value();
                                   ~~~~~~~~~~~~~~~~~~~~ ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:2611:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/Canvas.cc:75:58: error: too few arguments to function call, single argument 'context' was not specified
  if (info[1]->IsNumber()) height = info[1]->Uint32Value();
                                    ~~~~~~~~~~~~~~~~~~~~ ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:2611:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/Canvas.cc:76:51: error: no matching conversion for functional-style cast from 'v8::Local<v8::Value>' to 'String::Utf8Value'
  if (info[2]->IsString()) type = !strcmp("pdf", *String::Utf8Value(info[2]))
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:3046:5: note: candidate constructor not viable: no known conversion from
      'v8::Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st argument
    Utf8Value(const Utf8Value&) = delete;
    ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:3039:5: note: candidate constructor not viable: requires 2 arguments, but 1 was
      provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
../src/Canvas.cc:78:23: error: no matching conversion for functional-style cast from 'v8::Local<v8::Value>' to 'String::Utf8Value'
    : !strcmp("svg", *String::Utf8Value(info[2]))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:3046:5: note: candidate constructor not viable: no known conversion from
      'v8::Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st argument
    Utf8Value(const Utf8Value&) = delete;
    ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:3039:5: note: candidate constructor not viable: requires 2 arguments, but 1 was
      provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
../src/Canvas.cc:119:40: error: too few arguments to function call, single argument 'context' was not specified
    canvas->width = value->Uint32Value();
                    ~~~~~~~~~~~~~~~~~~ ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:2611:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/Canvas.cc:140:41: error: too few arguments to function call, single argument 'context' was not specified
    canvas->height = value->Uint32Value();
                     ~~~~~~~~~~~~~~~~~~ ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:2611:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/Canvas.cc:221:19: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    closure->pfn->Call(1, argv);
                  ^
../../nan/nan.h:1646:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/Canvas.cc:226:19: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    closure->pfn->Call(2, argv);
                  ^
../../nan/nan.h:1646:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/Canvas.cc:274:52: error: too few arguments to function call, single argument 'context' was not specified
          compression_level = info[1]->Uint32Value();
                              ~~~~~~~~~~~~~~~~~~~~ ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:2611:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/Canvas.cc:279:49: error: too few arguments to function call, single argument 'context' was not specified
            uint32_t tmp = info[1]->Uint32Value();
                           ~~~~~~~~~~~~~~~~~~~~ ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:2611:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/Canvas.cc:301:39: error: too few arguments to function call, single argument 'context' was not specified
        filter = info[2]->Uint32Value();
                 ~~~~~~~~~~~~~~~~~~~~ ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:2611:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/Canvas.cc:377:8: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
  Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)closure->fn, 3, argv);
       ^
../../nan/nan.h:958:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/Canvas.cc:396:52: error: too few arguments to function call, single argument 'context' was not specified
          compression_level = info[1]->Uint32Value();
                              ~~~~~~~~~~~~~~~~~~~~ ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8.h:2611:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/jakob/Library/Caches/node-gyp/12.11.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
15 warnings and 20 errors generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jakob/Projects/shortcut/server/node_modules/canvas
gyp ERR! node -v v12.11.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jakob/.npm/_logs/2019-12-07T23_18_35_740Z-debug.log
✘-1 ~/Projects/shortcut/server [master|✔] 

```

What were you expecting to happen?
----------------------------------
No errors to occur, the build to succeed, me to be able to check out `shortcut`.

**Comment by jfix** [comment]
I have installed `nvm` and downgraded my node version to `v8.16.2` and can confirm that the build now works. Howevr, the installed modules are no longer up to date and therefore `npm audit` finds a lot of vulnerabilities, not all of which could be fixed by `npm audit fix`. I will open another ticket to request an update of the code base.
